# Deployment configuration for Cloud Run
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cesiumjs-globe-viewer
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/PROJECT_ID/cesiumjs-app
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi